#!/bin/bash

set -e

rm_ldconfig() {
    rm -f /etc/ld.so.conf.d/hsa-rocr-dev.conf && ldconfig
}

case "$1" in
   remove)
       rm_ldconfig
       rm -rf @CPACK_PACKAGING_INSTALL_PREFIX@/include/hsa
   ;;
   purge)
   ;;
   *)
       exit 0
   ;;
esac

