//////////////////////////////////////////////////////////////////////////////////
//  THIS FILE IS AUTO-GENERATED BY PITGEN (vA)
//       !!!!  DO NOT EDIT BY HAND  !!!!
//////////////////////////////////////////////////////////////////////////////////
//   Project:						10xx or later
//   Description:
//
//   PM4 PacketType3 IT_OpCode Definitions
//   Extracted From ME and PFP F32 Microcode Jump Tables:
//
//////////////////////////////////////////////////////////////////////////////////
//
//  Trade secret of ATI Technologies, Inc.
//  Copyright 1999, ATI Technologies, Inc., (unpublished)
//
//  All rights reserved.  This notice is intended as a precaution against
//  inadvertent publication and does not imply publication or any waiver
//  of confidentiality.  The year included in the foregoing notice is the
//  year of creation of the work.
//////////////////////////////////////////////////////////////////////////////////

#ifndef PM4_IT_OPCODES_H
#define PM4_IT_OPCODES_H

enum IT_OpCodeType {
  IT_NOP = 0x10,
  IT_SET_BASE = 0x11,
  IT_CLEAR_STATE = 0x12,
  IT_INDEX_BUFFER_SIZE = 0x13,
  IT_DISPATCH_DIRECT = 0x15,
  IT_DISPATCH_INDIRECT = 0x16,
  IT_INDIRECT_BUFFER_END = 0x17,
  IT_INDIRECT_BUFFER_CNST_END = 0x19,
  IT_ALLOC_GDS__SI = 0x1B,
  IT_WRITE_GDS_RAM__SI = 0x1C,
  IT_ATOMIC_GDS = 0x1D,
  IT_ATOMIC__SI__VI = 0x1E,
  IT_OCCLUSION_QUERY = 0x1F,
  IT_SET_PREDICATION = 0x20,
  IT_REG_RMW = 0x21,
  IT_COND_EXEC = 0x22,
  IT_PRED_EXEC = 0x23,
  IT_DRAW_INDIRECT = 0x24,
  IT_DRAW_INDEX_INDIRECT = 0x25,
  IT_INDEX_BASE = 0x26,
  IT_DRAW_INDEX_2 = 0x27,
  IT_CONTEXT_CONTROL = 0x28,
  IT_INDEX_TYPE = 0x2A,
  IT_DRAW_INDIRECT_MULTI = 0x2C,
  IT_DRAW_INDEX_AUTO = 0x2D,
  IT_DRAW_INDEX_IMMD__SI = 0x2E,
  IT_NUM_INSTANCES = 0x2F,
  IT_DRAW_INDEX_MULTI_AUTO = 0x30,
  IT_INDIRECT_BUFFER_CNST_PRIV__SI = 0x31,
  IT_INDIRECT_BUFFER_PRIV = 0x32,
  IT_INDIRECT_BUFFER_CNST = 0x33,
  IT_STRMOUT_BUFFER_UPDATE = 0x34,
  IT_DRAW_INDEX_OFFSET_2 = 0x35,
  IT_WRITE_DATA = 0x37,
  IT_DRAW_INDEX_INDIRECT_MULTI = 0x38,
  IT_MEM_SEMAPHORE = 0x39,
  IT_MPEG_INDEX__SI = 0x3A,
  IT_COPY_DW__SI__CI = 0x3B,
  IT_WAIT_REG_MEM = 0x3C,
  IT_MEM_WRITE__SI = 0x3D,
  IT_INDIRECT_BUFFER = 0x3F,
  IT_COPY_DATA = 0x40,
  IT_CP_DMA = 0x41,
  IT_PFP_SYNC_ME = 0x42,
  IT_SURFACE_SYNC = 0x43,
  IT_ME_INITIALIZE = 0x44,
  IT_COND_WRITE = 0x45,
  IT_EVENT_WRITE = 0x46,
  IT_EVENT_WRITE_EOP = 0x47,
  IT_EVENT_WRITE_EOS = 0x48,
  IT_PREAMBLE_CNTL = 0x4A,
  IT_GFX_CNTX_UPDATE = 0x52,
  IT_BLK_CNTX_UPDATE = 0x53,
  IT_INCR_UPDT_STATE = 0x55,
  IT_ONE_REG_WRITE__SI = 0x57,
  IT_LOAD_SH_REG = 0x5F,
  IT_LOAD_CONFIG_REG = 0x60,
  IT_LOAD_CONTEXT_REG = 0x61,
  IT_SET_CONFIG_REG = 0x68,
  IT_SET_CONTEXT_REG = 0x69,
  IT_SET_SH_REG_DI = 0x72,
  IT_SET_CONTEXT_REG_INDIRECT = 0x73,
  IT_SET_SH_REG = 0x76,
  IT_SET_SH_REG_OFFSET = 0x77,
  IT_ME_WRITE__SI = 0x7A,
  IT_PFP_WRITE__SI = 0x7B,
  IT_SCRATCH_RAM_WRITE = 0x7D,
  IT_SCRATCH_RAM_READ = 0x7E,
  IT_CE_WRITE__SI = 0x7F,
  IT_LOAD_CONST_RAM = 0x80,
  IT_WRITE_CONST_RAM = 0x81,
  IT_WRITE_CONST_RAM_OFFSET__SI = 0x82,
  IT_DUMP_CONST_RAM = 0x83,
  IT_INCREMENT_CE_COUNTER = 0x84,
  IT_INCREMENT_DE_COUNTER = 0x85,
  IT_WAIT_ON_CE_COUNTER = 0x86,
  IT_WAIT_ON_DE_COUNTER__SI = 0x87,
  IT_WAIT_ON_DE_COUNTER_DIFF = 0x88,
  IT_SET_CE_DE_COUNTERS__SI = 0x89,
  IT_WAIT_ON_AVAIL_BUFFER__SI = 0x8A,
  IT_SWITCH_BUFFER = 0x8B,
  IT_FORWARD_HEADER = 0x7C,
  IT_ATOMIC_MEM__CI = 0x1E,
  IT_DRAW_PREAMBLE__CI__VI = 0x36,
  IT_RELEASE_MEM__CI__VI = 0x49,
  IT_DMA_DATA__CI__VI = 0x50,
  IT_ACQUIRE_MEM__CI__VI = 0x58,
  IT_REWIND__CI__VI = 0x59,
  IT_INTERRUPT__CI__VI = 0x5A,
  IT_LOAD_UCONFIG_REG__CI__VI = 0x5E,
  IT_SET_QUEUE_REG__CI__VI = 0x78,
  IT_SET_UCONFIG_REG__CI__VI = 0x79,
  IT_EOP_BUFFER_END__CI__VI = 0x18,
  IT_INTR_BUFFER_END__CI__VI = 0x1A,
  IT_RUN_LIST__CI = 0x3E,
  IT_SET_RESOURCES__CI__VI = 0xA0,
  IT_MAP_PROCESS__CI__VI = 0xA1,
  IT_MAP_QUEUES__CI__VI = 0xA2,
  IT_QUERY_STATUS__CI = 0xA3,
  IT_UNMAP_QUEUES__CI = 0xA4,
  IT_COND_PREEMPT__VI = 0x8E,
  IT_DISPATCH_DRAW_PREAMBLE__VI = 0x8C,
  IT_DISPATCH_DRAW__VI = 0x8D,
  IT_DISPATCH_DRAW_PREAMBLE_ACE__VI = 0x8C,
  IT_DISPATCH_DRAW_ACE__VI = 0x8D,
  IT_PRIME_ATCL2__VI = 0x8E,
  IT_UNMAP_QUEUES__VI = 0xA3,
  IT_QUERY_STATUS__VI = 0xA4,
  IT_RUN_LIST__VI = 0xA5,
};

#define PM4_TYPE_0 0
#define PM4_TYPE_2 2
#define PM4_TYPE_3 3

#endif  // PM4_IT_OPCODES_H
