#!/bin/bash -e

opencl_blit_file="$1"

if ! command -v xxd >/dev/null
then
    echo "xxd not found!"
    exit 1
fi

# Create the file in a temporary location and then move it in atomically
rm -rf "$opencl_blit_file.tmp"
{
cat <<EOF
//==============================================================================
//  This file is automatically generated during build process, don't modify it
//==============================================================================

namespace rocr {
namespace image {

EOF

for file in ocl_blit_object*
do
    xxd -i $file
    echo -e '\n'
done

cat <<EOF
} // namespace image
} // namespace rocr

EOF

} > "$opencl_blit_file.tmp"

# Move the file atomically into place, so make doesn't get half a file
# but only if it has changed. cmp -s is happy for one file not to exist
cmp -s "$opencl_blit_file.tmp" "$opencl_blit_file" ||
    mv -f "$opencl_blit_file.tmp" "$opencl_blit_file"
