//////////////////////////////////////////////////////////////////////////////////
//  THIS FILE IS AUTO-GENERATED BY PITGEN (vA)
//       !!!!  DO NOT EDIT BY HAND  !!!!
//////////////////////////////////////////////////////////////////////////////////
//   Project:						10xx or later
//   Description:
//
//   PM4 PacketType3 IT_OpCode Definitions
//   Extracted From ME and PFP F32 Microcode Jump Tables:
//
//////////////////////////////////////////////////////////////////////////////////
//
//  Trade secret of ATI Technologies, Inc.
//  Copyright 1999, ATI Technologies, Inc., (unpublished)
//
//  All rights reserved.  This notice is intended as a precaution against
//  inadvertent publication and does not imply publication or any waiver
//  of confidentiality.  The year included in the foregoing notice is the
//  year of creation of the work.
//////////////////////////////////////////////////////////////////////////////////

#ifndef PM4_IT_OPCODES_H
#define PM4_IT_OPCODES_H

namespace pm4_profile {
namespace gfx9 {

// typedef enum IT_OpCodeType {
enum IT_OpCodeType {
  IT_NOP = 0x10,
  IT_SET_BASE = 0x11,
  IT_CLEAR_STATE = 0x12,
  IT_INDEX_BUFFER_SIZE = 0x13,
  IT_DISPATCH_DIRECT = 0x15,
  IT_DISPATCH_INDIRECT = 0x16,
  IT_INDIRECT_BUFFER_END = 0x17,
  IT_INDIRECT_BUFFER_CNST_END = 0x19,
  IT_ATOMIC_GDS = 0x1D,
  IT_ATOMIC_MEM = 0x1E,
  IT_OCCLUSION_QUERY = 0x1F,
  IT_SET_PREDICATION = 0x20,
  IT_REG_RMW = 0x21,
  IT_COND_EXEC = 0x22,
  IT_PRED_EXEC = 0x23,
  IT_DRAW_INDIRECT = 0x24,
  IT_DRAW_INDEX_INDIRECT = 0x25,
  IT_INDEX_BASE = 0x26,
  IT_DRAW_INDEX_2 = 0x27,
  IT_CONTEXT_CONTROL = 0x28,
  IT_INDEX_TYPE = 0x2A,
  IT_DRAW_INDIRECT_MULTI = 0x2C,
  IT_DRAW_INDEX_AUTO = 0x2D,
  IT_NUM_INSTANCES = 0x2F,
  IT_DRAW_INDEX_MULTI_AUTO = 0x30,
  IT_INDIRECT_BUFFER_CNST = 0x33,
  IT_STRMOUT_BUFFER_UPDATE = 0x34,
  IT_DRAW_INDEX_OFFSET_2 = 0x35,
  IT_WRITE_DATA = 0x37,
  IT_DRAW_INDEX_INDIRECT_MULTI = 0x38,
  IT_MEM_SEMAPHORE = 0x39,
  IT_DRAW_INDEX_MULTI_INST = 0x3A,
  IT_WAIT_REG_MEM = 0x3C,
  IT_INDIRECT_BUFFER = 0x3F,
  IT_COND_INDIRECT_BUFFER = 0x3F,
  IT_COPY_DATA = 0x40,
  IT_PFP_SYNC_ME = 0x42,
  IT_ME_INITIALIZE = 0x44,
  IT_COND_WRITE = 0x45,
  IT_EVENT_WRITE = 0x46,
  IT_RELEASE_MEM = 0x49,
  IT_PREAMBLE_CNTL = 0x4A,
  IT_DMA_DATA = 0x50,
  IT_CONTEXT_REG_RMW = 0x51,
  IT_GFX_CNTX_UPDATE = 0x52,
  IT_BLK_CNTX_UPDATE = 0x53,
  IT_INCR_UPDT_STATE = 0x55,
  IT_ACQUIRE_MEM = 0x58,
  IT_REWIND = 0x59,
  IT_GEN_PDEPTE = 0x5B,
  IT_PRIME_UTCL2 = 0x5D,
  IT_LOAD_UCONFIG_REG = 0x5E,
  IT_LOAD_SH_REG = 0x5F,
  IT_LOAD_CONFIG_REG = 0x60,
  IT_LOAD_CONTEXT_REG = 0x61,
  IT_SET_CONFIG_REG = 0x68,
  IT_SET_CONTEXT_REG = 0x69,
  IT_SET_CONTEXT_REG_INDEX = 0x6A,
  IT_SET_SH_REG_DI = 0x72,
  IT_SET_SH_REG = 0x76,
  IT_SET_SH_REG_OFFSET = 0x77,
  IT_SET_QUEUE_REG = 0x78,
  IT_SET_UCONFIG_REG = 0x79,
  IT_SET_UCONFIG_REG_INDEX = 0x7A,
  IT_FORWARD_HEADER = 0x7C,
  IT_SCRATCH_RAM_WRITE = 0x7D,
  IT_SCRATCH_RAM_READ = 0x7E,
  IT_LOAD_CONST_RAM = 0x80,
  IT_WRITE_CONST_RAM = 0x81,
  IT_DUMP_CONST_RAM = 0x83,
  IT_INCREMENT_CE_COUNTER = 0x84,
  IT_INCREMENT_DE_COUNTER = 0x85,
  IT_WAIT_ON_CE_COUNTER = 0x86,
  IT_WAIT_ON_DE_COUNTER_DIFF = 0x88,
  IT_SWITCH_BUFFER = 0x8B,
  IT_DISPATCH_DRAW_PREAMBLE = 0x8C,
  IT_DISPATCH_DRAW = 0x8D,
  IT_COND_PREEMPT = 0x8E,
  IT_DRAW_MULTI_PREAMBLE = 0x8F,
  IT_FRAME_CONTROL = 0x90,
  IT_INDEX_ATTRIBUTES_INDIRECT = 0x91,
  IT_WAIT_REG_MEM64 = 0x93,
  IT_GET_LOD_STATS = 0x94,
  IT_COPY_DATA_RB = 0x96,
  IT_DMA_DATA_FILL_MULTI = 0x9A,
  IT_SET_SH_REG_INDEX = 0x9B,
  IT_EOP_BUFFER_END = 0x18,
  IT_INTR_BUFFER_END = 0x1A,
  IT_CP_DMA = 0x41,
  IT_SURFACE_SYNC = 0x43,
  IT_EVENT_WRITE_EOP = 0x47,
  IT_EVENT_WRITE_EOS = 0x48,
  IT_INTERRUPT = 0x5A,
  IT_INDIRECT_BUFFER_PASID = 0x5C,
  IT_LOAD_COMPUTE_STATE = 0x62,
  IT_SET_CONTEXT_REG_INDIRECT = 0x73,
  IT_DISPATCH_DRAW_PREAMBLE_ACE = 0x8C,
  IT_DISPATCH_DRAW_ACE = 0x8D,
  IT_HDP_FLUSH = 0x95,
  IT_SECURE_CONTROL = 0x97,
  IT_INVALIDATE_TLBS = 0x98,
  IT_AQL_PACKET = 0x99,
  IT_SET_RESOURCES = 0xA0,
  IT_MAP_PROCESS = 0xA1,
  IT_MAP_QUEUES = 0xA2,
  IT_UNMAP_QUEUES = 0xA3,
  IT_QUERY_STATUS = 0xA4,
  IT_RUN_LIST = 0xA5,
  IT_MAP_PROCESS_VM = 0xA6
};
//} IT_OpCodeType;

#define PM4_TYPE_0 0
#define PM4_TYPE_2 2
#define PM4_TYPE_3 3

}  // gfx9
}  // pm4_profile

#endif  // PM4_IT_OPCODES_H
