OPENCL_DEPTH = ../..

include $(OPENCL_DEPTH)/runtimenew/runtimedefs

SUBDIRS = NBody
SUBDIRS += DwtHarr1D
SUBDIRS += BitionicSort
SUBDIRS += BinarySearch
SUBDIRS += BlackScholes
SUBDIRS += FloydWarshall 
SUBDIRS += MatrixTranspose
SUBDIRS += MatrixMultiplication

include $(OPENCL_DEPTH)/runtimenew/runtimerules
