OPENCL_DEPTH = ../..

include $(OPENCL_DEPTH)/hsadefs

SUBDIRS = NBody
#SUBDIRS += DwtHarr1D
SUBDIRS += BitionicSort
SUBDIRS += BinarySearch
SUBDIRS += BlackScholes
SUBDIRS += FloydWarshall 
SUBDIRS += FastWalshTransform
SUBDIRS += MatrixTranspose
SUBDIRS += MatrixMultiplication
SUBDIRS += MonteCarloAsian
SUBDIRS += SimpleConvolution

include $(OPENCL_DEPTH)/hsarules
